language: android
jdk: oraclejdk8

# Travis has Xenial builds as default -> https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
# Android builds are not yet supported on Xenial, use trusty instead
dist: trusty

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"

script:
  - ./gradlew clean build